### ISSUE TITLE
[FEAT] iOS 2차 과제 수정

### ISSUE THREAD

**Issue by yangwon9616** [29th-WE-SOPT-iOS-Part/JoeYangWon#11]
## 📌  Feature Issue

- 다른 계정으로 로그인하기 에러 해결
- 업로드 영상이 issues에서 바로 보이지 않는 문제 (mp4를 gif로 업로드)
위의 2가지 이슈를 해결하여 다시 풀리퀘 날립니다 

![Simulator Screen Recording - iPhone 12 - 2021-10-21 at 23 40 49](https://user-images.githubusercontent.com/66239314/138305459-f4eb4386-8b56-45b1-acc9-b0758030d2c5.gif)

## 📝  To-do

- [ ] 다른 계정으로 로그인하기 에러 해결
- [ ] 업로드 영상이 issues에서 바로 보이지 않는 문제 (mp4를 gif로 업로드)
- [ ] 버튼 radius 설정
