### ISSUE TITLE
[FEAT] iOS 2차 과제 수정

### ISSUE THREAD

**Issue by yangwon9616** [29th-WE-SOPT-iOS-Part/JoeYangWon#12]
## 📝  To-do

- [x] 다른 계정으로 로그인 에러 해결
- [x] 버튼 radius값 설정
- [x] issues에 mp4 영상을 gif로 업로드
