### ISSUE TITLE
[FEAT] iOS 1차 과제 금잔디 리뷰 반영

### ISSUE THREAD

**Issue by yangwon9616** [29th-WE-SOPT-iOS-Part/JoeYangWon#7]
## 📌  Feature Issue

금잔디파 태현선생님의 훌륭한 리뷰를 보고 감동을 받아 바로 피드백을 반영할 수밖에 없는 부분입니다

## 📝  To-do

- [ ] 버튼에 텍스트 추가해서 버튼클림범위 넓히기
- [ ] 조건문을 toggle로 변경하기
- [ ] viewDidLoad 부분의 코드를 함수로 넣어서 간결하게 정리하기
